IF EXISTS (SELECT * FROM dbo.[GroundRentPdf] WHERE [AcknowledgementNumber] = @AcknowledgementNumber AND [AccountId] = @AccountId)
BEGIN
UPDATE dbo.[GroundRentPdf] SET
[AddressId] = @AddressId, 
[AccountId] = @AccountId, 
[AcknowledgementNumber] = @AcknowledgementNumber, 
[DocumentFiledType] = @DocumentFiledType, 
[DateTimeFiled] = @DateTimeFiled, 
[PdfPageCount] = @PdfPageCount, 
[Book] = @Book, 
[Page] = @Page, 
[ClerkInitials] = @ClerkInitials, 
[YearRecorded] = @YearRecorded,
[PdfDownloaded] = @PdfDownloaded,
[AzureFormRecognizerCategory] = @AzureFormRecognizerCategory,
[GroundRentPaymentAmount] = @GroundRentPaymentAmount,
[GroundLeaseCreatedPriorTo1884] = @GroundLeaseCreatedPriorTo1884,
[GroundLeaseCreatedBetween1884And1888] = @GroundLeaseCreatedBetween1884And1888,
[GroundLeaseCreatedBetween1888And1982] = @GroundLeaseCreatedBetween1888And1982,
[GroundLeaseCreated1982OrLater] = @GroundLeaseCreated1982OrLater,
[PaymentFrequencyAnnually] = @PaymentFrequencyAnnually,
[PaymentFrequencySemiAnnually] = @PaymentFrequencySemiAnnually,
[PaymentFrequencyQuarterly] = @PaymentFrequencyQuarterly,
[PaymentFrequencyOther] = @PaymentFrequencyOther,
[PaymentFrequencyAnnuallyDate] = @PaymentFrequencyAnnuallyDate,
[PaymentFrequencySemiAnnuallyDate] = @PaymentFrequencySemiAnnuallyDate,
[PaymentFrequencyQuarterlyDate] = @PaymentFrequencyQuarterlyDate,
[PaymentFrequencyOtherDate] = @PaymentFrequencyOtherDate,
[FormPreparedDate] = @FormPreparedDate,
[TenantName] = @TenantName,
[TenantStreet] = @TenantStreet,
[TenantCity] = @TenantCity,
[TenantState] = @TenantState,
[TenantZipCode] = @TenantZipCode,
[Holder1Name] = @Holder1Name,
[Holder1Street] = @Holder1Street,
[Holder1City] = @Holder1City,
[Holder1State] = @Holder1State,
[Holder1ZipCode] = @Holder1ZipCode,
[Holder2Name] = @Holder2Name,
[Holder2Street] = @Holder2Street,
[Holder2City] = @Holder2City,
[Holder2State] = @Holder2State,
[Holder2ZipCode] = @Holder2ZipCode,
[Payable1Name] = @Payable1Name,
[Payable2Name] = @Payable2Name,
[PayableStreet] = @PayableStreet,
[PayableCity] = @PayableCity,
[PayableState] = @PayableState,
[PayableZipCode] = @PayableZipCode
WHERE [AcknowledgementNumber] = @AcknowledgementNumber AND [AccountId] = @AccountId;
END
ELSE
BEGIN
SET NOCOUNT ON
INSERT INTO dbo.[GroundRentPdf] 
([AddressId], 
[AccountId], 
[AcknowledgementNumber], 
[DocumentFiledType], 
[DateTimeFiled], 
[PdfPageCount], 
[Book], 
[Page], 
[ClerkInitials], 
[YearRecorded],
[PdfDownloaded],
[AzureFormRecognizerCategory],
[GroundRentPaymentAmount],
[GroundLeaseCreatedPriorTo1884],
[GroundLeaseCreatedBetween1884And1888],
[GroundLeaseCreatedBetween1888And1982],
[GroundLeaseCreated1982OrLater],
[PaymentFrequencyAnnually],
[PaymentFrequencySemiAnnually],
[PaymentFrequencyQuarterly],
[PaymentFrequencyOther],
[PaymentFrequencyAnnuallyDate],
[PaymentFrequencySemiAnnuallyDate],
[PaymentFrequencyQuarterlyDate],
[PaymentFrequencyOtherDate],
[FormPreparedDate],
[TenantName],
[TenantStreet],
[TenantCity],
[TenantState],
[TenantZipCode],
[Holder1Name],
[Holder1Street],
[Holder1City],
[Holder1State],
[Holder1ZipCode],
[Holder2Name],
[Holder2Street],
[Holder2City],
[Holder2State],
[Holder2ZipCode],
[Payable1Name],
[Payable2Name],
[PayableStreet],
[PayableCity],
[PayableState],
[PayableZipCode])
VALUES
(@AddressId, 
@AccountId, 
@AcknowledgementNumber, 
@DocumentFiledType, 
@DateTimeFiled, 
@PdfPageCount, 
@Book, 
@Page, 
@ClerkInitials, 
@YearRecorded,
@PdfDownloaded,
@AzureFormRecognizerCategory,
@GroundRentPaymentAmount,
@GroundLeaseCreatedPriorTo1884,
@GroundLeaseCreatedBetween1884And1888,
@GroundLeaseCreatedBetween1888And1982,
@GroundLeaseCreated1982OrLater,
@PaymentFrequencyAnnually,
@PaymentFrequencySemiAnnually,
@PaymentFrequencyQuarterly,
@PaymentFrequencyOther,
@PaymentFrequencyAnnuallyDate,
@PaymentFrequencySemiAnnuallyDate,
@PaymentFrequencyQuarterlyDate,
@PaymentFrequencyOtherDate,
@FormPreparedDate,
@TenantName,
@TenantStreet,
@TenantCity,
@TenantState,
@TenantZipCode,
@Holder1Name,
@Holder1Street,
@Holder1City,
@Holder1State,
@Holder1ZipCode,
@Holder2Name,
@Holder2Street,
@Holder2City,
@Holder2State,
@Holder2ZipCode,
@Payable1Name,
@Payable2Name,
@PayableStreet,
@PayableCity,
@PayableState,
@PayableZipCode);
SELECT CAST(SCOPE_IDENTITY() AS INT);
SET NOCOUNT OFF
END